### ISSUE TITLE
class选择器

### ISSUE THREAD

**Issue by 642495539** [642495539/learn-feng#6]
```css
 #class1 div{
	
	background-color:red;
}

 div#class1{
	
	background-color:red;
}
```
//教材上说是第一种语法正确，但是在chrome中第二种可以，第一种不行，why

**Comment by gutenye** [comment]
2种都正确的, 但是HTML没给出来, 我不知道什么情况

**Comment by gutenye** [comment]
```css
 #class1 div{

    background-color:red;
}
```
下面HTML用的.
```html
<div id="class1">
  <div>hello world</div>
</div>
```
```css
 div#class1{
    background-color:red;
}
```
给
```html
<div id="class1">hello world</div>
```
